CREATE TABLE IF NOT EXISTS `ai_solution` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'AI solution id',
  `record_id` bigint NOT NULL COMMENT 'AI recognition record id',
  `result_id` bigint NOT NULL COMMENT 'AI recognition result id',
  `user_id` bigint NOT NULL COMMENT 'User id',
  `plot_id` bigint DEFAULT NULL COMMENT 'Plot id',
  `camera_id` bigint DEFAULT NULL COMMENT 'Camera id',
  `solution_title` varchar(120) NOT NULL COMMENT 'Solution title',
  `solution_summary` varchar(500) DEFAULT NULL COMMENT 'Solution summary',
  `solution_detail` text DEFAULT NULL COMMENT 'Solution detail',
  `priority_level` tinyint DEFAULT 2 COMMENT 'Priority: 1 low, 2 normal, 3 high, 4 urgent',
  `generate_task` tinyint DEFAULT 0 COMMENT 'Whether task generation is requested',
  `task_generated` tinyint DEFAULT 0 COMMENT 'Whether farm task was generated',
  `farm_task_id` bigint DEFAULT NULL COMMENT 'Generated farm task id',
  `status` tinyint DEFAULT 1 COMMENT 'Status: 1 active, 2 task generated, 3 archived',
  `remark` varchar(500) DEFAULT NULL COMMENT 'Remark',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'Create time',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Update time',
  PRIMARY KEY (`id`),
  KEY `idx_ai_solution_record` (`record_id`),
  KEY `idx_ai_solution_result` (`result_id`),
  KEY `idx_ai_solution_user` (`user_id`),
  KEY `idx_ai_solution_plot` (`plot_id`),
  KEY `idx_ai_solution_camera` (`camera_id`),
  KEY `idx_ai_solution_task` (`farm_task_id`),
  KEY `idx_ai_solution_status_time` (`status`, `create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='AI recognition solution table';

CREATE TABLE IF NOT EXISTS `farm_task_record` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'Farm task execution record id',
  `task_id` bigint NOT NULL COMMENT 'Farm task id',
  `operator_id` bigint NOT NULL COMMENT 'Operator user id',
  `action_type` tinyint NOT NULL COMMENT 'Action type: 1 start, 2 complete, 3 feedback, 4 optimize',
  `action_content` varchar(500) DEFAULT NULL COMMENT 'Action content',
  `result_status` tinyint DEFAULT NULL COMMENT 'Result status: 1 valid, 2 partial, 3 invalid',
  `feedback_score` tinyint DEFAULT NULL COMMENT 'Feedback score 1-5',
  `feedback_detail` text DEFAULT NULL COMMENT 'Feedback detail',
  `optimize_suggestion` text DEFAULT NULL COMMENT 'Optimization suggestion',
  `before_status` tinyint DEFAULT NULL COMMENT 'Task status before action',
  `after_status` tinyint DEFAULT NULL COMMENT 'Task status after action',
  `execute_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'Execution time',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'Create time',
  PRIMARY KEY (`id`),
  KEY `idx_farm_task_record_task` (`task_id`),
  KEY `idx_farm_task_record_operator` (`operator_id`),
  KEY `idx_farm_task_record_action` (`action_type`),
  KEY `idx_farm_task_record_time` (`execute_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Farm task execution feedback table';

CREATE TABLE IF NOT EXISTS `alert_event` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'Alert event id',
  `user_id` bigint NOT NULL COMMENT 'Owner user id',
  `plot_id` bigint DEFAULT NULL COMMENT 'Plot id',
  `device_id` bigint DEFAULT NULL COMMENT 'Device id',
  `batch_id` bigint DEFAULT NULL COMMENT 'Planting batch id',
  `alert_type` tinyint NOT NULL COMMENT 'Alert type',
  `alert_title` varchar(100) NOT NULL COMMENT 'Alert title',
  `alert_content` text DEFAULT NULL COMMENT 'Alert content',
  `metric_code` varchar(50) DEFAULT NULL COMMENT 'Metric code',
  `metric_name` varchar(50) DEFAULT NULL COMMENT 'Metric name',
  `metric_value` decimal(10,3) DEFAULT NULL COMMENT 'Metric value',
  `metric_unit` varchar(20) DEFAULT NULL COMMENT 'Metric unit',
  `threshold_min` decimal(10,3) DEFAULT NULL COMMENT 'Threshold minimum',
  `threshold_max` decimal(10,3) DEFAULT NULL COMMENT 'Threshold maximum',
  `alert_level` tinyint DEFAULT 1 COMMENT 'Alert level: 1 normal, 2 important, 3 urgent',
  `source_type` varchar(50) DEFAULT NULL COMMENT 'Source type',
  `source_id` bigint DEFAULT NULL COMMENT 'Source id',
  `process_status` tinyint DEFAULT 1 COMMENT 'Process status',
  `handler_id` bigint DEFAULT NULL COMMENT 'Handler user id',
  `handle_time` datetime DEFAULT NULL COMMENT 'Handle time',
  `handle_result` varchar(255) DEFAULT NULL COMMENT 'Handle result',
  `trigger_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'Trigger time',
  `status` tinyint DEFAULT 1 COMMENT 'Status',
  `remark` varchar(255) DEFAULT NULL COMMENT 'Remark',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'Create time',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Update time',
  PRIMARY KEY (`id`),
  KEY `idx_alert_user_id` (`user_id`),
  KEY `idx_alert_plot_id` (`plot_id`),
  KEY `idx_alert_type` (`alert_type`),
  KEY `idx_alert_level` (`alert_level`),
  KEY `idx_alert_process_status` (`process_status`),
  KEY `idx_alert_trigger_time` (`trigger_time`),
  KEY `idx_alert_source` (`source_type`, `source_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Alert event table';

CREATE TABLE IF NOT EXISTS `notification` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'Notification id',
  `user_id` bigint NOT NULL COMMENT 'Receiver user id',
  `title` varchar(100) NOT NULL COMMENT 'Notification title',
  `content` text DEFAULT NULL COMMENT 'Notification content',
  `notice_type` tinyint NOT NULL COMMENT 'Notice type',
  `ref_type` varchar(50) DEFAULT NULL COMMENT 'Reference type',
  `ref_id` bigint DEFAULT NULL COMMENT 'Reference id',
  `alert_id` bigint DEFAULT NULL COMMENT 'Alert event id',
  `level` tinyint DEFAULT 1 COMMENT 'Level: 1 normal, 2 important, 3 urgent',
  `is_read` tinyint DEFAULT 0 COMMENT 'Read flag',
  `read_time` datetime DEFAULT NULL COMMENT 'Read time',
  `send_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'Send time',
  `status` tinyint DEFAULT 1 COMMENT 'Status',
  `remark` varchar(255) DEFAULT NULL COMMENT 'Remark',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'Create time',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Update time',
  PRIMARY KEY (`id`),
  KEY `idx_notification_user_id` (`user_id`),
  KEY `idx_notification_notice_type` (`notice_type`),
  KEY `idx_notification_is_read` (`is_read`),
  KEY `idx_notification_send_time` (`send_time`),
  KEY `idx_notification_ref` (`ref_type`, `ref_id`),
  KEY `idx_notification_alert_id` (`alert_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Notification table';
