-- Add install/offline/fault timestamps for IoT device uptime calculation.
-- Device code is now generated by the smart_plant backend in D_001 format.

ALTER TABLE `iot_device`
  ADD COLUMN `install_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '设备安装时间' AFTER `health_status`,
  ADD COLUMN `offline_time` datetime NULL DEFAULT NULL COMMENT '最近一次离线时间' AFTER `install_time`,
  ADD COLUMN `fault_time` datetime NULL DEFAULT NULL COMMENT '最近一次故障或维护时间' AFTER `offline_time`;

UPDATE `iot_device`
SET `install_time` = COALESCE(`last_online_time`, `last_heartbeat_time`, `create_time`, `install_time`),
    `offline_time` = CASE
      WHEN `online_status` = 0 THEN COALESCE(`last_data_time`, `update_time`, `create_time`, `install_time`)
      ELSE NULL
    END,
    `fault_time` = CASE
      WHEN `health_status` IN (1, 2) THEN COALESCE(`update_time`, `create_time`, `install_time`)
      ELSE NULL
    END;

ALTER TABLE `iot_device`
  ADD INDEX `idx_iot_device_install_time` (`install_time`),
  ADD INDEX `idx_iot_device_offline_time` (`offline_time`),
  ADD INDEX `idx_iot_device_fault_time` (`fault_time`);

ALTER TABLE `iot_device`
  ADD CONSTRAINT `chk_iot_device_offline_time_after_install` CHECK (`offline_time` IS NULL OR `offline_time` >= `install_time`),
  ADD CONSTRAINT `chk_iot_device_fault_time_after_install` CHECK (`fault_time` IS NULL OR `fault_time` >= `install_time`);
