const assert = require('node:assert/strict')
const fs = require('node:fs')

const page = fs.readFileSync('pages/index/mine.vue', 'utf8')

assert.match(page, /\.mine-page\s*\{[\s\S]*radial-gradient\(ellipse at 84% 15%[\s\S]*linear-gradient\(180deg, #9edfd6 0%, #dff6f1 27%, #f0faf7 58%, #f5fdf9 100%\);/)
assert.match(page, /\.mine-page::before,[\s\S]*\.mine-page::after/)
assert.match(page, /\.page-hero\s*\{[\s\S]*background:\s*transparent;/)
assert.doesNotMatch(page, /\.page-hero::(?:before|after)/)
assert.match(page, /\.page-hero\s*\{[\s\S]*padding:\s*calc\(var\(--status-bar-height\) \+ 108rpx\) 44rpx 0;/)
assert.match(page, /\.profile-avatar\s*\{[\s\S]*width:\s*118rpx;[\s\S]*height:\s*118rpx;/)
assert.match(page, /\.profile-info\s*\{[\s\S]*margin-left:\s*31rpx;/)
assert.match(page, /\.profile-account\s*\{[\s\S]*font-size:\s*17px;/)
assert.match(page, /\.quick-grid\s*\{[\s\S]*gap:\s*30rpx;/)
assert.match(page, /\.quick-card\s*\{[\s\S]*height:\s*154rpx;[\s\S]*border-radius:\s*26rpx;/)
assert.match(page, /\.menu-row\s*\{[\s\S]*height:\s*115rpx;/)
assert.match(page, /\.menu-row:not\(:last-child\)::before/)
assert.match(page, /role="button" aria-label="编辑个人信息"/)
assert.match(page, /hover-class="entry-pressed"/)
