const assert = require('node:assert/strict')
const { readFileSync } = require('node:fs')
const { join } = require('node:path')

// 静态回归确保农场主个人中心入口、编辑路由和资料接口保持完整。
const root = join(__dirname, '..')
const minePage = readFileSync(join(root, 'pages', 'index', 'mine.vue'), 'utf8')
const technicianMine = readFileSync(join(root, 'pages', 'technician', 'mine.vue'), 'utf8')
const expertMine = readFileSync(join(root, 'pages', 'expert', 'mine.vue'), 'utf8')
const profilePage = readFileSync(join(root, 'pages', 'secondPage', 'profile', 'index.vue'), 'utf8')
const authApi = readFileSync(join(root, 'api', 'clientAuth.js'), 'utf8')
const routes = readFileSync(join(root, 'pages.json'), 'utf8')

assert.match(minePage, /@tap="openProfile"/)
assert.match(technicianMine, /@tap="openProfile"/)
assert.match(expertMine, /@tap="openProfile"/)
assert.match(minePage, /pages\/secondPage\/profile\/index/)
assert.match(routes, /pages\/secondPage\/profile\/index/)
assert.match(profilePage, /form\.username/)
assert.match(profilePage, /form\.phone/)
assert.match(profilePage, /form\.nickname/)
assert.match(profilePage, /form\.gender/)
assert.match(profilePage, /form\.email/)
assert.match(profilePage, /form\.remark/)
assert.match(profilePage, /farm_owner.*user.*technician.*expert/)
assert.match(profilePage, /uploadCurrentClientAvatar/)
assert.match(profilePage, /updateCurrentClientProfile/)
assert.match(authApi, /client\/auth\/profile\/avatar/)
assert.match(authApi, /client\/auth\/profile/)
